services:
  blog-next-app:
    build: .
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    env_file:
      - ./config.env
